<!DOCTYPE html>
<html lang="ru">
<head>
    <link rel="stylesheet" href="/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/style.css">
    <meta charset="utf-8">
    <title>Менеджер задач</title>
</head>

<body>
<div class="container ">
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
  <h5 class="my-0 mr-md-auto font-weight-normal"><a href="/">Менеджер задач</a></h5>
  <a class="btn btn-outline-primary" href="/tasks/create">Создать задачу</a>
  <?php if (!isset($_SESSION['admin'])) : ?>
  <a class="btn btn-outline-primary" href="/login">Войти</a>
  <?php else :?> 
  <a class="btn btn-outline-primary" href="/logout">Выйти</a>
  <?php endif ?>
</div>

