<form action="/login" method="POST">
<?php if(isset($_SESSION['errors']['access'])) : ?>
  <div class="alert alert-danger" role="alert">
    <?=$_SESSION['errors']['access']?>
  </div>
<?php endif; ?>
<?php unset($_SESSION['errors']['access']); ?>
<div class="form-group row">
    <label for="login" class="col-sm-2 col-form-label">Имя пользователя:</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" id="login" name="login" value="<?php if (isset($_SESSION['data'])): ?>  <?=htmlspecialchars($_SESSION['data']['login']) ??  ''?> <?php endif ?>">
      <?php if (isset($_SESSION['errors']['login'])) : ?>
        <div class="alert alert-danger"><?= $_SESSION['errors']['login'] ?></div>
        <?php unset($_SESSION['errors']['login']); ?>
      <?php endif; ?>
      <?php unset($_SESSION['data']['login']); ?>
    </div>
  </div>
  <div class="form-group row">
    <label for="email" class="col-sm-2 col-form-label">Пароль:</label>
    <div class="col-sm-10">
      <input type="password" class="form-control" id="password" name="password" value="">
      <?php if (isset($_SESSION['errors']['password'])) : ?>
        <div class="alert alert-danger"><?= $_SESSION['errors']['password'] ?></div>
        <?php unset($_SESSION['errors']['password']); ?>
      <?php endif; ?>
    </div>
  </div>


  
  <div class="form-group row">
    <div class="col-sm-10">
      <button type="submit" class="btn btn-primary">Войти</button>
    </div>
  </div>
</form>
</body>

</html>