<form action="/tasks/store" method="POST">
<div class="form-group row">
    <label for="name" class="col-sm-2 col-form-label">Имя пользователя:</label>
    <div class="col-sm-10">
<input type="text" class="form-control" id="name" name="name" value="<?php if (isset($_SESSION['data'])): ?>  <?=htmlspecialchars($_SESSION['data']['name']) ??  ''?> <?php endif ?>">
      <?php if (isset($_SESSION['errors']['name'])) : ?>
        <div class="alert alert-danger"><?= $_SESSION['errors']['name'] ?></div>
        <?php unset($_SESSION['errors']['name']); ?>
      <?php endif; ?>
    </div>
  </div>
  <div class="form-group row">
    <label for="email" class="col-sm-2 col-form-label">Email:</label>
    <div class="col-sm-10">
      <input type="email" class="form-control" id="email" name="email" value="<?php if (isset($_SESSION['data'])): ?>  <?=htmlspecialchars($_SESSION['data']['email']) ??  ''?> <?php endif ?>">
      <?php if (isset($_SESSION['errors']['email'])) : ?>
        <div class="alert alert-danger"><?= $_SESSION['errors']['email'] ?></div>
        <?php unset($_SESSION['errors']['email']); ?>
      <?php endif; ?>
    </div>
  </div>
  <div class="form-group row">
    <label for="content" class="col-sm-2 col-form-label">Текст задачи:</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" id="content" name="content" value="<?php if (isset($_SESSION['data'])): ?>  <?=htmlspecialchars($_SESSION['data']['content']) ??  ''?> <?php endif ?>">
      <?php if (isset($_SESSION['errors']['content'])) : ?>
        <div class="alert alert-danger"><?= $_SESSION['errors']['content'] ?></div>
        <?php unset($_SESSION['errors']['content']); ?>
      <?php endif; ?>
      <?php unset($_SESSION['data']); ?>
    </div>
  </div>

  
  <div class="form-group row">
    <div class="col-sm-10">
      <button type="submit" class="btn btn-primary">Создать</button>
    </div>
  </div>
</form>
</body>

</html>